// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lijnbcaebkabtuxfcaaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpam5iY2FlYmthYnR1eGZjYWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjA2NTYsImV4cCI6MjA2NzYzNjY1Nn0.lp2vMFFqko5yk2MZ1BeChC_2x0U9ZnU_5FsR9Kelt9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});